# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-workflow-config
data:
  config.yaml: |+
    env:
      dev: false

    log:
      level: debug

    db:
      host: forge-pg-cluster.postgres.svc.cluster.local
      port: 5432
      name: forge
      user: forge
      passwordPath: /var/secrets/db/auth/password

    temporal:
      host: temporal-frontend-headless.temporal.svc.cluster.local
      port: 7233
      serverName: localhost
      namespace: cloud
      queue: cloud
      tls:
        certPath: /var/secrets/temporal/certs/client-cloud/tls.crt
        keyPath: /var/secrets/temporal/certs/client-cloud/tls.key
        caPath: /var/secrets/temporal/certs/client-cloud/ca.crt
      encryptionKey: "carbide-rest"

    ngc:
      api:
        baseUrl: https://test.com

    siteManager:
      svcEndpoint: "https://sitemgr.cloud-site-manager:8100/v1/site"
    
    tracing:
      enabled: false
      serviceName: cloud-workflow
