# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-api-config
data:
  config.yaml: |+
    env:
      dev: false
      disconnected: true

    api:
      name: carbide
      route:
        version: v2

    log:
      level: info
      sentry:
        dsn: ""

    db:
      host: forge-pg-cluster.postgres.svc.cluster.local
      port: 5432
      name: forge
      user: forge
      passwordPath: /var/secrets/db/auth/password

    temporal:
      host: temporal-frontend-headless.temporal.svc.cluster.local
      port: 7233
      serverName: localhost
      namespace: cloud
      queue: cloud
      tls:
        enabled: true
        certPath: /var/secrets/temporal/certs/client-cloud/tls.crt
        keyPath: /var/secrets/temporal/certs/client-cloud/tls.key
        caPath: /var/secrets/temporal/certs/client-cloud/ca.crt
      encryptionKey: "carbide"

    auth:
      - name: kas-legacy
        origin: 1 # TokenOriginKas
        url: https://authn.nvidia.com/pubJWKS
        issuer: "authn.nvidia.com"
        serviceAccount: false
      - name: kas-ssa
        origin: 2 # TokenOriginSsa
        url: https://example.ssa.nvidia.com/.well-known/jwks.json
        issuer: "https://example.ssa.nvidia.com"
        serviceAccount: false

    siteManager:
      enabled: true
      svcEndpoint: "https://sitemgr.cloud-site-manager:8100/v1/site"

    site:
      phoneHomeUrl: http://169.254.169.254:7777/latest/meta-data/phone_home

    metrics:
      enabled: true
      port: 9360

    tracing:
      enabled: false
      serviceName: cloud-api
      
    keycloak:
      enabled: false
