# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

# carbide-rest-site-manager Service
apiVersion: v1
kind: Service
metadata:
  name: carbide-rest-site-manager
  labels:
    app: carbide-rest-site-manager
spec:
  type: ClusterIP
  ports:
    - port: 8100
      targetPort: 8100
      name: https
  selector:
    app: carbide-rest-site-manager

