# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

env:
  dev: true
  disconnected: true

log:
  level: debug
  sentry:
    dsn: ""

db:
  host: localhost
  port: 30432
  name: forge
  user: forge
  password: forge

temporal:
  host: localhost
  port: 30233
  serverName: server.temporal.test.com
  namespace: cloud
  queue: cloud
  tls:
    enabled: true
    certPath: certs/client-cloud/tls.crt
    keyPath: certs/client-cloud/tls.key
    caPath: certs/client-cloud/ca.crt
  encryptionKey: "local-dev" # Must match encryption key in workflow module

auth:
  - name: kas
    origin: 1 # TokenOriginKas
    url: https://authn.nvidia.com/pubJWKS
    issuer: "authn.nvidia.com"
    serviceAccount: false

siteManager:
  enabled: false
  svcEndpoint: "https://sitemgr.cloud-site-manager:8100/v1/site"

metrics:
  enabled: true
  port: 9360

tracing:
  enabled: false
  serviceName: cloud-api

keycloak:
  enabled: false
  baseURL: http://keycloak.keycloak.svc.cluster.local:8080
  externalBaseURL: https://keycloak.test.com
  realm: forge
  clientID: forge-cloud
  clientSecretPath: /var/secrets/keycloak/client-secret
  serviceAccount: true

rateLimiter:
  enabled: false
  rate: 10.0        # requests per second
  burst: 30         # maximum burst size
  expiresIn: 180    # expiration time in seconds (3 minutes)
